version: '3.8'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_SUPABASE_URL
      - NEXT_PUBLIC_SUPABASE_ANON_KEY
      - NEXT_PUBLIC_SENTRY_DSN
    volumes:
      - .:/app:cached
    command: npm run dev
